Improved check for allowance
Just-Ape-Studios/just-ape-studios-contracts pull request #7
Opened 2023-11-14 20:52 UTC by EdinyangaOttoho

Key points

- If allowance is supplied for all 'Id's, checking a single token Id in every instance should return true whether or not the single token Id is approved.

2023-11-15 11:55 UTC, 0xnetfox requested changes
It would be nice if you reword the commit message in order to explain in the title what was improved

e.g. "modified allowance message to always check for all token permissions"

2023-11-15 11:55 UTC, 0xnetfox commented on data.rs
> +            },
nitpicking but I believe this could be simplified as:

```rust
Some(token) => self.is_allowed_single(owner, operator, token) || self.is_allowed_all(owner, operator),
```

2023-11-15 12:34 UTC, EdinyangaOttoho commented on data.rs
> +            },
Sure. That works. Maybe make a push on this regard

2023-11-16 10:53 UTC, 0xnetfox approved these changes

2023-11-16 10:55 UTC, merged